/* Regenerate web/public/ui_data.json before dev or build.
 *
 * The file is generated by scripts/export_ui_data.py and is gitignored, so a
 * fresh clone has none and the coverage and review pages would have nothing to
 * read. This hook keeps the interpreter choice portable: a local checkout
 * usually has .venv, CI has only the system python, and a contributor may set
 * TERE4AI_PYTHON explicitly.
 *
 * Exit rules, chosen so the hook can never be the reason a build fails when
 * usable data already exists: succeed if the export runs, succeed with a
 * warning if the export cannot run but the file is already present, and fail
 * with instructions only when there is no data and no way to generate it.
 */

import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import path from "node:path";
import process from "node:process";

const webDir = process.cwd();
const repoRoot = path.resolve(webDir, "..");
const target = path.join(webDir, "public", "ui_data.json");
const script = path.join("scripts", "export_ui_data.py");

const candidates = [
  process.env.TERE4AI_PYTHON,
  path.join(repoRoot, ".venv", "bin", "python"),
  path.join(repoRoot, ".venv", "Scripts", "python.exe"),
  "python3",
  "python",
].filter(Boolean);

function runnable(candidate) {
  return path.isAbsolute(candidate) ? existsSync(candidate) : true;
}

let ran = false;
for (const interpreter of candidates) {
  if (!runnable(interpreter)) continue;
  const result = spawnSync(interpreter, [script], {
    cwd: repoRoot,
    stdio: "inherit",
  });
  if (result.error || result.status !== 0) continue;
  console.log(`ui_data.json regenerated with ${interpreter}`);
  ran = true;
  break;
}

if (!ran) {
  if (existsSync(target)) {
    console.warn(
      "could not regenerate ui_data.json (no usable python interpreter found); " +
        "using the existing file, which may be stale",
    );
  } else {
    console.error(
      "ui_data.json is missing and could not be generated. Run this from the " +
        "repository root, then retry:\n  .venv/bin/python scripts/export_ui_data.py\n" +
        "or set TERE4AI_PYTHON to a python that has the project installed.",
    );
    process.exit(1);
  }
}
