"""Meta tests for scripts/check_traceability.py (Section 17 CI gate).

Runs the checker as a subprocess, both against the real tree and against
small fixture repos via --root. While parallel agents are still adding
modules, the real-tree run may legitimately fail on missing expected
decisions; the real-tree test therefore asserts only the non-gating parts
(generation works, no unknown REF or DEC ids, no forbidden dashes) and
uses fixtures for full exit-0 and exit-1 coverage.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "check_traceability.py"


def run_checker(root: Path | None = None) -> subprocess.CompletedProcess:
    cmd = [sys.executable, str(SCRIPT)]
    if root is not None:
        cmd += ["--root", str(root)]
    return subprocess.run(
        cmd, cwd=REPO_ROOT, capture_output=True, text=True, timeout=120
    )


def make_fake_repo(
    base: Path,
    module_grounded_by: str = "REF-01",
    module_body: str = "VALUE = 1\n",
) -> Path:
    """Create a minimal repo the checker can run against via --root."""
    root = base / "fakerepo"
    (root / "docs").mkdir(parents=True)
    (root / "src" / "pkg").mkdir(parents=True)
    (root / "scripts").mkdir(parents=True)
    (root / "tests").mkdir(parents=True)

    (root / "docs" / "architecture.md").write_text(
        "# Arch\n"
        "\n"
        "## 16. Traceability matrix\n"
        "\n"
        "- DEC-01: fixture decision one. grounded_by REF-01.\n"
        "- DEC-02: fixture decision two, not yet built.\n"
        "\n"
        "## 17. Convention\n"
        "\n"
        "Tags as usual.\n",
        encoding="utf-8",
    )
    (root / "docs" / "references.md").write_text(
        "# References\n"
        "\n"
        "**[REF-01]** OFF. Fixture source.\n"
        "Grounds: the fixture decision.\n",
        encoding="utf-8",
    )
    (root / "scripts" / "ci_expected_decisions.json").write_text(
        json.dumps({"milestone": "M1", "expected": ["DEC-01"]}),
        encoding="utf-8",
    )
    (root / "src" / "pkg" / "mod.py").write_text(
        '"""Fixture module.\n'
        "\n"
        "@implements: DEC-01\n"
        f"@grounded_by: {module_grounded_by}\n"
        '"""\n'
        "\n" + module_body,
        encoding="utf-8",
    )
    return root


def test_real_tree_generates_matrix_and_has_no_unknown_ids():
    result = run_checker()
    out = result.stdout + result.stderr

    generated = REPO_ROOT / "docs" / "traceability.md"
    assert generated.exists(), f"docs/traceability.md not generated:\n{out}"
    content = generated.read_text(encoding="utf-8")
    assert "GENERATED by scripts/check_traceability.py" in content

    # sources.py exists and tags DEC-12, so it must be implemented or partial.
    dec12_row = next(
        (line for line in content.splitlines() if line.startswith("| DEC-12 ")),
        None,
    )
    assert dec12_row is not None, f"no DEC-12 row in traceability.md:\n{content}"
    assert ("implemented" in dec12_row) or ("partial" in dec12_row)

    # Non-gating assertions: no unknown ids and no forbidden dashes,
    # regardless of whether expected decisions are all tagged yet.
    assert "[unknown-ref]" not in out, out
    assert "[unknown-dec]" not in out, out
    assert "[dash]" not in out, out

    # If the run failed, the only acceptable reason while parallel agents
    # are mid-flight is a missing expected decision.
    if result.returncode != 0:
        fail_lines = [ln for ln in out.splitlines() if ln.startswith("FAIL ")]
        assert fail_lines, out
        assert all("[missing-expected]" in ln for ln in fail_lines), out


def test_fixture_repo_passes_and_generates_matrix(tmp_path):
    root = make_fake_repo(tmp_path)
    result = run_checker(root=root)
    out = result.stdout + result.stderr
    assert result.returncode == 0, out

    generated = root / "docs" / "traceability.md"
    assert generated.exists()
    content = generated.read_text(encoding="utf-8")
    dec01_row = next(
        line for line in content.splitlines() if line.startswith("| DEC-01 ")
    )
    assert "implemented" in dec01_row
    assert "REF-01" in dec01_row
    assert "src/pkg/mod.py" in dec01_row
    dec02_row = next(
        line for line in content.splitlines() if line.startswith("| DEC-02 ")
    )
    assert "not_started" in dec02_row


def test_fixture_repo_with_bogus_ref_fails(tmp_path):
    root = make_fake_repo(tmp_path, module_grounded_by="REF-99")
    result = run_checker(root=root)
    out = result.stdout + result.stderr
    assert result.returncode == 1, out
    assert "[unknown-ref]" in out
    assert "REF-99" in out


def test_fixture_repo_with_em_dash_fails(tmp_path):
    root = make_fake_repo(
        tmp_path, module_body='COMMENT = "bad punctuation \N{EM DASH} here"\n'
    )
    result = run_checker(root=root)
    out = result.stdout + result.stderr
    assert result.returncode == 1, out
    assert "[dash]" in out
    assert "src/pkg/mod.py" in out


def _git(root: Path, *args: str) -> None:
    subprocess.run(
        ["git", "-C", str(root), *args],
        check=True,
        capture_output=True,
        env={
            "GIT_AUTHOR_NAME": "t",
            "GIT_AUTHOR_EMAIL": "t@t",
            "GIT_COMMITTER_NAME": "t",
            "GIT_COMMITTER_EMAIL": "t@t",
            "HOME": str(root),
            "PATH": "/usr/bin:/bin",
        },
    )


def test_untracked_files_stay_out_of_matrix_and_gates(tmp_path):
    """B55: the checker scans the git index, so an untracked file with tags,
    dashes, or an absolute home path must neither write matrix rows nor fail
    a gate; it does not exist on a fresh clone."""
    root = make_fake_repo(tmp_path)
    _git(root, "init", "-q")
    _git(root, "add", "-A")
    _git(root, "commit", "-qm", "fixture")
    home = "/" + "home/"
    (root / "scripts" / "untracked_probe.py").write_text(
        '"""@implements: DEC-02\n@grounded_by: REF-99\n"""\n'
        f'P = "{home}nobody/x"\n',
        encoding="utf-8",
    )
    result = run_checker(root=root)
    out = result.stdout + result.stderr
    assert result.returncode == 0, out
    content = (root / "docs" / "traceability.md").read_text(encoding="utf-8")
    assert "untracked_probe" not in content
    assert "[unknown-ref]" not in out
    assert "[abs-path]" not in out


def test_gate5_absolute_home_path_fails(tmp_path):
    """B53 Gate 5: a tracked source hardcoding an absolute home path fails.
    The fixture repo is not a git checkout, so the filesystem fallback makes
    every file 'tracked'."""
    home = "/" + "home/"
    root = make_fake_repo(tmp_path, module_body=f'VALUE = "{home}somebody/data"\n')
    result = run_checker(root=root)
    out = result.stdout + result.stderr
    assert result.returncode == 1, out
    assert "[abs-path]" in out
    assert "src/pkg/mod.py" in out
