"""
Pydantic Models for Generated Requirements

This module defines the output of the Specification Agent - formal
requirements with full traceability to EU AI Act and HLEG sources.

Each requirement:
  - Has a formal statement (SHALL/SHOULD/MAY language)
  - Is anchored to specific EU AI Act articles and paragraphs
  - Is aligned with HLEG principles and subtopics
  - Includes verification criteria
  - Has priority and category metadata

TRUSTWORTHINESS PRINCIPLES:

  - Every requirement traces to specific legal text
  - HLEG alignment includes relevance scores and subtopics
  - Verification criteria are derived from article requirements
  - Categories map to Chapter III structure
"""

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field

from .citations import Citation


class RequirementCategory(str, Enum):
    """
    Categories of requirements based on EU AI Act Chapter III structure.

    Section 2 (Technical requirements): Articles 8-15
    Section 3 (Obligations): Articles 16-27
    Section 4 (Notifying authorities): Articles 28-39
    Section 5 (Standards, conformity): Articles 40-49
    """

    # Section 2: Technical requirements (Articles 8-15)
    RISK_MANAGEMENT = "risk_management"  # Article 9
    DATA_GOVERNANCE = "data_governance"  # Article 10
    DOCUMENTATION = "documentation"  # Article 11
    RECORD_KEEPING = "record_keeping"  # Article 12
    TRANSPARENCY = "transparency"  # Article 13
    HUMAN_OVERSIGHT = "human_oversight"  # Article 14
    ACCURACY_ROBUSTNESS = "accuracy_robustness"  # Article 15

    # Section 3: Obligations (Articles 16-27)
    PROVIDER_OBLIGATIONS = "provider_obligations"  # Articles 16-22
    DEPLOYER_OBLIGATIONS = "deployer_obligations"  # Articles 26-27
    IMPORTER_OBLIGATIONS = "importer_obligations"  # Article 23
    DISTRIBUTOR_OBLIGATIONS = "distributor_obligations"  # Article 24
    PRODUCT_INTEGRATION = "product_integration"  # Article 25

    # Article 50 (for LIMITED risk)
    TRANSPARENCY_LIMITED = "transparency_limited"  # Article 50

    # Conformity (Articles 40-49)
    CONFORMITY = "conformity"

    # General
    GENERAL = "general"


class RequirementPriority(str, Enum):
    """
    Priority levels for requirements.

    Based on legal obligation strength and safety impact.
    """

    CRITICAL = "critical"  # Mandatory, safety-critical
    HIGH = "high"  # Mandatory per regulation
    MEDIUM = "medium"  # Recommended by regulation
    LOW = "low"  # Best practice, not mandatory


class RequirementType(str, Enum):
    """
    Type of requirement based on obligation strength.

    Maps to SHALL/SHOULD/MAY language in formal requirements.
    """

    MANDATORY = "mandatory"  # SHALL - required by regulation
    RECOMMENDED = "recommended"  # SHOULD - strongly recommended
    OPTIONAL = "optional"  # MAY - permitted/encouraged


class ConflictDetail(BaseModel):
    """
    Details of a conflict between two requirements.

    Used by ValidationAgent to report inconsistencies.
    """

    requirement_id_1: str = Field(
        description="ID of the first conflicting requirement."
    )
    requirement_id_2: str = Field(
        description="ID of the second conflicting requirement."
    )
    conflict_type: str = Field(
        description="Type of conflict (e.g., 'contradiction', 'redundancy', 'overlap')."
    )
    explanation: str = Field(
        description="Detailed explanation of the conflict and why it's problematic."
    )
    suggested_resolution: Optional[str] = Field(
        default=None,
        description="Optional suggestion for resolving the conflict."
    )


class InvalidCitationDetail(BaseModel):
    """
    Details of an invalid citation found during validation.

    Used by ValidationAgent to report citation errors.
    """

    requirement_id: str = Field(
        description="ID of the requirement containing the invalid citation."
    )
    citation_reference: str = Field(
        description="The reference string of the invalid citation (e.g., 'Article 9(1)')."
    )
    citation_type: str = Field(
        description="Type of citation (e.g., 'eu_ai_act', 'hleg', 'recital')."
    )
    reason: str = Field(
        description="Reason why the citation is invalid (e.g., 'Article does not exist', 'Text mismatch')."
    )
    expected_text: Optional[str] = Field(
        default=None,
        description="The expected text from the source, if available."
    )
    actual_text: Optional[str] = Field(
        default=None,
        description="The actual quoted text in the citation."
    )


class GeneratedRequirement(BaseModel):
    """
    A single requirement generated by the Specification Agent.

    This is the core output of TERE4AI - a formal requirement that is:
      - Derived from EU AI Act articles
      - Aligned with HLEG principles
      - Verifiable through specific criteria
      - Traceable to source documents

    Example:
      ID: REQ-001
      Title: Risk Management System
      Statement: The system SHALL implement a continuous risk management
                 process throughout its entire lifecycle...
      EU AI Act Citations: Article 9(1), Article 9(2)(a)
      HLEG Citations: Technical Robustness (0.95), Accountability (0.82)
    """

    id: str = Field(
        description="Unique requirement identifier, e.g. 'REQ-001', 'REQ-002'."
    )
    title: str = Field(
        description="Short descriptive title, e.g. 'Risk Management System'."
    )
    statement: str = Field(
        description=(
            "Full formal requirement text using SHALL/SHOULD/MAY language. "
            "Should be clear, testable, and grounded in source articles."
        )
    )

    # Classification
    category: RequirementCategory = Field(
        description="Category based on EU AI Act Chapter III structure."
    )
    priority: RequirementPriority = Field(
        description="Priority level based on legal obligation and safety impact."
    )
    requirement_type: RequirementType = Field(
        default=RequirementType.MANDATORY,
        description="Type based on obligation strength (SHALL/SHOULD/MAY)."
    )

    # Legal anchoring (THE KEY FEATURE)
    eu_ai_act_citations: List[Citation] = Field(
        default_factory=list,
        description=(
            "Citations to EU AI Act articles, paragraphs, and points "
            "that ground this requirement. Must not be empty."
        )
    )
    hleg_citations: List[Citation] = Field(
        default_factory=list,
        description=(
            "Citations to HLEG requirements and subtopics that align "
            "with this requirement. Includes relevance scores."
        )
    )
    supporting_recitals: List[Citation] = Field(
        default_factory=list,
        description=(
            "Recital citations that provide context for this requirement."
        )
    )

    # Context and rationale
    rationale: str = Field(
        description=(
            "Explanation of why this requirement exists and how it "
            "derives from the cited articles."
        )
    )
    context: Optional[str] = Field(
        default=None,
        description=(
            "Domain-specific context for how this requirement applies "
            "to the specific AI system being analyzed."
        )
    )

    # Verification
    verification_criteria: List[str] = Field(
        default_factory=list,
        description=(
            "Specific criteria for verifying compliance with this requirement. "
            "Derived from article text and regulatory guidance."
        )
    )
    verification_method: Optional[str] = Field(
        default=None,
        description=(
            "Suggested method for verification, e.g. 'documentation audit', "
            "'testing', 'code review', 'third-party assessment'."
        )
    )

    # Traceability metadata
    derived_from_articles: List[str] = Field(
        default_factory=list,
        description="List of article numbers this requirement derives from."
    )
    addresses_hleg_principles: List[str] = Field(
        default_factory=list,
        description="List of HLEG requirement IDs this addresses."
    )
    addresses_hleg_subtopics: List[str] = Field(
        default_factory=list,
        description="List of HLEG subtopic IDs this addresses."
    )

    # Optional refinement
    parent_requirement_id: Optional[str] = Field(
        default=None,
        description=(
            "If this is a sub-requirement, the ID of the parent. "
            "Used for hierarchical requirement structures."
        )
    )
    related_requirements: List[str] = Field(
        default_factory=list,
        description="IDs of related requirements (cross-references)."
    )

    def get_primary_article(self) -> Optional[str]:
        """Get the primary article this requirement derives from."""
        if self.derived_from_articles:
            return self.derived_from_articles[0]
        return None

    def get_citation_count(self) -> int:
        """Get total number of citations."""
        return (
            len(self.eu_ai_act_citations)
            + len(self.hleg_citations)
            + len(self.supporting_recitals)
        )

    def get_hleg_relevance_summary(self) -> dict[str, float]:
        """Get HLEG principles with their relevance scores."""
        summary: dict[str, float] = {}
        for citation in self.hleg_citations:
            if citation.requirement_id and citation.relevance_score:
                if citation.requirement_id not in summary:
                    summary[citation.requirement_id] = citation.relevance_score
                else:
                    # Take max relevance if multiple citations to same principle
                    summary[citation.requirement_id] = max(
                        summary[citation.requirement_id],
                        citation.relevance_score
                    )
        return summary

    def format_statement(self) -> str:
        """Format requirement statement with priority indicator."""
        priority_markers = {
            RequirementPriority.CRITICAL: "🔴",
            RequirementPriority.HIGH: "🟠",
            RequirementPriority.MEDIUM: "🟡",
            RequirementPriority.LOW: "🟢",
        }
        marker = priority_markers.get(self.priority, "")
        return f"{marker} [{self.id}] {self.statement}"


class ValidationResult(BaseModel):
    """
    Result of requirement validation by the Validation Agent.

    Checks completeness, consistency, and traceability of generated
    requirements against the applicable legal framework.
    """

    # Coverage metrics
    article_coverage: float = Field(
        ge=0.0,
        le=1.0,
        description="Proportion of applicable articles covered by requirements (0.0-1.0)."
    )
    hleg_coverage: float = Field(
        ge=0.0,
        le=1.0,
        description="Proportion of HLEG principles addressed (0.0-1.0)."
    )
    subtopic_coverage: float = Field(
        ge=0.0,
        le=1.0,
        description="Proportion of HLEG subtopics addressed (0.0-1.0)."
    )

    # Coverage details
    covered_articles: List[str] = Field(
        default_factory=list,
        description="List of article numbers covered by requirements."
    )
    missing_articles: List[str] = Field(
        default_factory=list,
        description="List of applicable articles not covered."
    )
    covered_hleg_principles: List[str] = Field(
        default_factory=list,
        description="List of HLEG requirement IDs addressed."
    )
    missing_hleg_principles: List[str] = Field(
        default_factory=list,
        description="List of HLEG requirements not addressed."
    )
    covered_subtopics: List[str] = Field(
        default_factory=list,
        description="List of HLEG subtopic IDs addressed."
    )

    # Consistency checks
    has_conflicts: bool = Field(
        default=False,
        description="Whether any requirements conflict with each other."
    )
    conflicts: List[ConflictDetail] = Field(
        default_factory=list,
        description="List of conflicting requirement pairs with explanation."
    )

    # Citation validity
    all_citations_valid: bool = Field(
        default=True,
        description="Whether all citations reference valid source content."
    )
    invalid_citations: List[InvalidCitationDetail] = Field(
        default_factory=list,
        description="List of invalid citations with details."
    )

    # Summary
    is_complete: bool = Field(
        default=False,
        description="Whether the requirement set is complete (all articles covered)."
    )
    is_consistent: bool = Field(
        default=True,
        description="Whether the requirement set is internally consistent."
    )
    is_valid: bool = Field(
        default=True,
        description="Whether all citations are valid."
    )

    # Recommendations
    recommendations: List[str] = Field(
        default_factory=list,
        description="Suggestions for improving the requirement set."
    )

    def is_acceptable(self) -> bool:
        """Check if validation results are acceptable for output."""
        return (
            self.article_coverage >= 0.8
            and self.hleg_coverage >= 0.7
            and self.is_consistent
            and self.is_valid
        )
