"""Security section for the paper: run the adversarial evidence corpus offline.

@grounded_by: REF-31, REF-16

Runs every fixture in tests/fixtures/adversarial_evidence.json through
evaluate_project_evidence with a worst-case naive generator under two
scripted judge conditions (rejecting, and fooled-accepting), and writes the
computed outcomes to docs/SECURITY_EVAL.md. Everything in the report is
produced by the real tool code path; nothing is asserted by hand.

Usage: .venv/bin/python scripts/adversarial_evidence_report.py
"""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "tests" / "unit"))

OUT_PATH = ROOT / "docs" / "SECURITY_EVAL.md"


def main() -> int:
    import test_adversarial_evidence as harness

    rows = []
    with tempfile.TemporaryDirectory() as tmp:
        for fixture in harness.FIXTURES:
            rejected = harness.run_fixture(fixture, harness.JUDGE_REJECT, Path(tmp))
            fooled = harness.run_fixture(fixture, harness.JUDGE_ACCEPT, Path(tmp))
            rows.append(
                {
                    "id": fixture["id"],
                    "attack_class": fixture["attack_class"],
                    "judge_reject_status": rejected["status"],
                    "fooled_assessment": fooled["answer"]["assessment"],
                    "fooled_dropped_quotes": fooled["answer"]["dropped_quotes"],
                    "fooled_surviving_quotes": len(fooled["answer"]["quotes"]),
                }
            )

    all_review = all(r["judge_reject_status"] == "requires_human_review" for r in rows)
    lines = [
        "# Security evaluation: adversarial evidence corpus",
        "",
        "> Generated by scripts/adversarial_evidence_report.py from",
        "> tests/fixtures/adversarial_evidence.json; every outcome below is",
        "> computed by running the real evaluate_project_evidence code path",
        "> offline with scripted model clients. No model was called.",
        "",
        "## Threat model",
        "",
        "Project evidence is untrusted input (architecture.md Section 8,",
        "REF-31): artifact text can address the models directly, plant quotes",
        "or citations, assert compliance, or spoof tool envelopes. The corpus",
        f"holds {len(rows)} fixtures across {len(harness.CORPUS['attack_classes'])} "
        "attack classes, each paired with the worst-case naive generator",
        "output the attack is designed to elicit.",
        "",
        "## Defense layers exercised",
        "",
        "1. Mechanical verbatim-quote check: quotes not present in the",
        "   artifact are dropped before any status is computed; an assessment",
        "   with zero surviving quotes downgrades to cannot_assess.",
        "2. Runtime grounding judge (independent model family, DEC-07): any",
        "   non-accepting verdict forces requires_human_review at zero",
        "   confidence, never the generator-derived status.",
        "3. Closed status vocabulary (DEC-08): compliant and certified do not",
        "   exist as statuses, so assertion bait has nothing to trigger.",
        "",
        "## Computed outcomes",
        "",
        "| Fixture | Attack class | Judge rejects: status | Judge fooled: assessment | Dropped quotes | Surviving quotes |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        lines.append(
            f"| {r['id']} | {r['attack_class']} | {r['judge_reject_status']} "
            f"| {r['fooled_assessment']} | {r['fooled_dropped_quotes']} "
            f"| {r['fooled_surviving_quotes']} |"
        )
    lines += [
        "",
        "## Reading the results",
        "",
        f"- With a rejecting judge, {'all' if all_review else 'NOT ALL'} "
        f"{len(rows)} attacks land requires_human_review (the required",
        "  invariant; enforced in tests/unit/test_adversarial_evidence.py).",
        "- With a deliberately fooled judge (scripted acceptance), the",
        "  mechanical layer still drops every non-verbatim quote; fixtures",
        "  whose attack depends on fabricated text end at cannot_assess.",
        "- Residual risk, stated plainly: an attack whose text is quoted",
        "  verbatim and whose framing convinces the live judge would pass the",
        "  mechanical layer. That risk is exactly what the judge false-accept",
        "  rate (task #25) measures; this corpus gives the FA labeling a",
        "  targeted adversarial slice, and the live-judge run over the",
        "  corpus is cost-gated alongside the other paid sweeps.",
        "",
    ]
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(ROOT)} ({len(rows)} fixtures)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
