"""Generate the graph census page from the published dumps.

@implements: DEC-10 (partial: graph census documentation)
@grounded_by: REF-08

Usage:
  .venv/bin/python scripts/graph_census.py [--out docs/graph_census.md]

Deterministic; reads only the versioned dumps (data/graph_dumps), never the
live database, so the census always describes the reproducible artifact. The
output is GENERATED; never hand-edit.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

DUMPS = ROOT / "data" / "graph_dumps"


def _sha16(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def census(layer1: dict, norms: dict, alignments: dict | None) -> dict:
    node_types = Counter(n["type"] for n in layer1.get("nodes", []))
    edge_types = Counter(e["edge_type"] for e in layer1.get("edges", []))
    provenance = Counter(
        e.get("provenance_class", "unknown") for e in layer1.get("edges", [])
    )
    norm_verdicts = Counter(
        n.get("judge_verdict") or "none" for n in norms.get("norms", [])
    )
    result = {
        "build_id": layer1.get("build", {}).get("build_id", "unknown"),
        "norms_build_id": norms.get("build", {}).get("build_id", "unknown"),
        "layer1_nodes": sum(node_types.values()),
        "layer1_edges": sum(edge_types.values()),
        "node_types": dict(node_types.most_common()),
        "edge_types": dict(edge_types.most_common()),
        "provenance_classes": dict(provenance.most_common()),
        "norms_total": len(norms.get("norms", [])),
        "norm_verdicts": dict(norm_verdicts.most_common()),
    }
    if alignments is not None:
        assertions = alignments.get("assertions", [])
        result["assertions_total"] = len(assertions)
        result["assertion_verdicts"] = dict(
            Counter(a.get("judge_verdict") or "none" for a in assertions).most_common()
        )
        result["alignment_relations"] = dict(
            Counter(a.get("relation_type") or "unknown" for a in assertions).most_common()
        )
    return result


def _table(title: str, mapping: dict) -> list[str]:
    lines = [f"## {title}", "", "| item | count |", "| --- | --- |"]
    lines += [f"| {k} | {v} |" for k, v in mapping.items()]
    lines.append("")
    return lines


def render(data: dict, checksums: dict[str, str]) -> str:
    lines = [
        "# Graph census",
        "",
        "> GENERATED by scripts/graph_census.py from the versioned dumps;",
        "> never hand-edit. Regenerate after any pipeline re-run.",
        "",
        f"- Layer 1 build: {data['build_id']}",
        f"- Norms build: {data['norms_build_id']}",
        f"- Layer 1: {data['layer1_nodes']} nodes, {data['layer1_edges']} edges",
        f"- Norms: {data['norms_total']} "
        f"(accepted {data['norm_verdicts'].get('accepted', 0)})",
    ]
    if "assertions_total" in data:
        lines.append(
            f"- Alignment assertions: {data['assertions_total']} "
            f"(accepted {data['assertion_verdicts'].get('accepted', 0)})"
        )
    lines += ["", "## Input dumps (sha256, first 16 hex)", ""]
    lines += [f"- {name}: {digest}" for name, digest in checksums.items()]
    lines.append("")
    lines += _table("Layer 1 node types", data["node_types"])
    lines += _table("Layer 1 edge types", data["edge_types"])
    lines += _table("Edge provenance classes", data["provenance_classes"])
    lines += _table("Norm judge verdicts", data["norm_verdicts"])
    if "assertion_verdicts" in data:
        lines += _table("Assertion judge verdicts", data["assertion_verdicts"])
        lines += _table("Alignment relation types", data["alignment_relations"])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=ROOT / "docs" / "graph_census.md")
    args = parser.parse_args(argv)

    layer1_path = DUMPS / "layer1.json"
    norms_path = DUMPS / "norms_core.json"
    alignments_path = DUMPS / "alignments_core.json"

    layer1 = json.loads(layer1_path.read_text(encoding="utf-8"))
    norms = json.loads(norms_path.read_text(encoding="utf-8"))
    alignments = (
        json.loads(alignments_path.read_text(encoding="utf-8"))
        if alignments_path.is_file()
        else None
    )
    data = census(layer1, norms, alignments)
    checksums = {
        p.name: _sha16(p)
        for p in (layer1_path, norms_path, alignments_path)
        if p.is_file()
    }
    args.out.write_text(render(data, checksums) + "\n", encoding="utf-8")
    print(f"wrote {args.out.relative_to(ROOT)}")
    print(
        f"  layer1 {data['layer1_nodes']} nodes / {data['layer1_edges']} edges | "
        f"norms {data['norms_total']} | assertions {data.get('assertions_total', 'n/a')}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
