"""Generate the norm near-duplicate report from a norms dump.

@implements: DEC-03 (partial: norm de-duplication hygiene)
@grounded_by: REF-11, REF-12

Usage:
  .venv/bin/python scripts/norm_dedup_report.py \
      [--norms data/graph_dumps/norms_core.json] [--out docs/norm_dedup_report.md]

Deterministic (no model calls). The report is GENERATED; regenerate it after
any norms re-extraction, never hand-edit.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from tere4ai.extract_norms.dedup import find_near_duplicates, summarize  # noqa: E402


def render(pairs, summary, norms_path: Path) -> str:
    lines = [
        "# Norm near-duplicate report",
        "",
        "> GENERATED by scripts/norm_dedup_report.py; never hand-edit.",
        f"> Source dump: {norms_path.name}. Rule-based (token Jaccard over",
        "> action plus object, blocked by article, actor, deontic type).",
        "> Candidates are surfaced for human decision, never auto-merged.",
        "",
        "## Summary",
        "",
    ]
    lines += [f"- {k}: {v}" for k, v in summary.items()]
    lines += [
        "",
        "## Flagged pairs (most similar first)",
        "",
        "| similarity | band | norm_a | norm_b | article | actor | deontic | verdicts |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for p in pairs:
        lines.append(
            "| {similarity} | {band} | {norm_a} | {norm_b} | {article} | "
            "{actor} | {deontic_type} | {v} |".format(v=", ".join(p["verdicts"]), **p)
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--norms", type=Path, default=ROOT / "data" / "graph_dumps" / "norms_core.json"
    )
    parser.add_argument(
        "--out", type=Path, default=ROOT / "docs" / "norm_dedup_report.md"
    )
    args = parser.parse_args(argv)

    norms = json.loads(args.norms.read_text(encoding="utf-8"))["norms"]
    pairs = find_near_duplicates(norms)
    summary = summarize(pairs, total_norms=len(norms))
    args.out.write_text(render(pairs, summary, args.norms), encoding="utf-8")
    print(f"wrote {args.out.relative_to(ROOT)}")
    for k, v in summary.items():
        print(f"  {k}: {v}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
