"""Repeat-run variance report over two ablation runs (#60).

@implements: DEC-11 (partial: repeat-run variance study)
@grounded_by: REF-15, REF-16

Compares two runs of the same ladder over the same items and the same
elicited-features cache, so the difference between them is provider-side
nondeterminism (temperature 0 is not a determinism guarantee), not input
drift. Per strategy it computes, from the per-item results only:

- risk-label flip rate on gold-labelled classification items (a flip is
  any change, including commit <-> abstain), plus both accuracies and
  both selective accuracies;
- citation stability: mean per-item Jaccard similarity of the emitted
  citation sets, over items where either run cited anything;
- QA answer stability: the fraction of QA items whose answer_text is
  byte-identical across runs (a coarse, honest lower bound; semantic
  equivalence is not judged here);
- the determinism check: the graph conditions classify via deterministic
  rules over fixed features, so their flip count is expected to be 0 and
  any nonzero value is a bug to investigate, not variance to report.

Usage:
  .venv/bin/python scripts/variance_report.py \
      --run-a eval/results/ablation_full_checkpoint.jsonl \
      --run-b eval/results/ablation_variance_checkpoint.jsonl \
      --benchmark data/snapshots/benchmark/full_payload.json \
      [--out docs/variance_study.md]
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

_spec = importlib.util.spec_from_file_location(
    "ablation_deepdive", ROOT / "scripts" / "ablation_deepdive.py"
)
_dd = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_dd)
load_results = _dd.load_results
gold_risk_by_item = _dd.gold_risk_by_item
analyse_strategy = _dd.analyse_strategy

DEFAULT_OUT = ROOT / "docs" / "variance_study.md"
GRAPH_STRATEGIES = ("graph_no_judge", "graph_build_judge", "graph_full")


def _label(result: dict[str, Any] | None) -> str:
    if not result:
        return "no_prediction"
    return result.get("risk_category") or "no_prediction"


def _jaccard(a: set[str], b: set[str]) -> float:
    if not a and not b:
        return 1.0
    return len(a & b) / len(a | b)


def compare_strategy(
    run_a: dict[str, dict[str, Any]],
    run_b: dict[str, dict[str, Any]],
    gold: dict[str, str],
) -> dict[str, Any]:
    common = sorted(set(run_a) & set(run_b))
    flips = []
    for item_id in common:
        if item_id not in gold:
            continue
        la, lb = _label(run_a[item_id]), _label(run_b[item_id])
        if la != lb:
            flips.append({"item": item_id, "run_a": la, "run_b": lb})
    labelled = [i for i in common if i in gold]

    cited = 0
    jaccard_sum = 0.0
    for item_id in common:
        ca = set(run_a[item_id].get("citations") or [])
        cb = set(run_b[item_id].get("citations") or [])
        if ca or cb:
            cited += 1
            jaccard_sum += _jaccard(ca, cb)

    qa_ids = [i for i in common if i not in gold]
    qa_identical = sum(
        1
        for i in qa_ids
        if (run_a[i].get("answer_text") or "") == (run_b[i].get("answer_text") or "")
    )

    a, b = analyse_strategy(run_a, gold), analyse_strategy(run_b, gold)
    return {
        "common_items": len(common),
        "labelled_items": len(labelled),
        "label_flips": len(flips),
        "flip_rate": len(flips) / len(labelled) if labelled else 0.0,
        "flip_details": flips,
        "accuracy_a": a["overall_accuracy"],
        "accuracy_b": b["overall_accuracy"],
        "selective_accuracy_a": a["abstention"]["selective_accuracy"],
        "selective_accuracy_b": b["abstention"]["selective_accuracy"],
        "citing_items": cited,
        "citation_jaccard_mean": jaccard_sum / cited if cited else None,
        "qa_items": len(qa_ids),
        "qa_answer_identical": qa_identical,
    }


def render_markdown(
    run_a_path: Path, run_b_path: Path, comparisons: dict[str, dict[str, Any]]
) -> str:
    lines = [
        "# Repeat-run variance study (task 60)",
        "",
        "> Generated by scripts/variance_report.py from "
        f"{run_a_path.name} (run A) and {run_b_path.name} (run B);",
        "> every number is computed from the per-item results. Both runs used",
        "> the same items and the same frozen elicited-features cache, so the",
        "> deltas below measure provider-side nondeterminism of the ladder",
        "> only, not input drift and not elicitation variance (held fixed by",
        "> design; elicitation variance is a separate, unmeasured axis).",
        "",
        "| Strategy | Label flips | Flip rate | Acc A | Acc B | Sel. acc A | Sel. acc B | Citation Jaccard | QA identical |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for name, c in comparisons.items():
        jac = (
            f"{c['citation_jaccard_mean']:.3f}"
            if c["citation_jaccard_mean"] is not None
            else "n/a"
        )
        lines.append(
            f"| {name} | {c['label_flips']}/{c['labelled_items']} "
            f"| {c['flip_rate']:.3f} | {c['accuracy_a']:.3f} | {c['accuracy_b']:.3f} "
            f"| {c['selective_accuracy_a']:.3f} | {c['selective_accuracy_b']:.3f} "
            f"| {jac} | {c['qa_answer_identical']}/{c['qa_items']} |"
        )
    lines.append("")

    determinism_broken = [
        name for name in GRAPH_STRATEGIES
        if name in comparisons and comparisons[name]["label_flips"] > 0
    ]
    if determinism_broken:
        lines += [
            "## DETERMINISM CHECK FAILED",
            "",
            "The graph conditions classify deterministically from fixed",
            f"features, yet flipped labels in: {', '.join(determinism_broken)}.",
            "This is a bug to investigate, not run variance.",
            "",
        ]
    else:
        lines += [
            "Determinism check: the graph conditions flipped 0 labels, as the",
            "deterministic classifier over fixed features requires.",
            "",
        ]

    for name, c in comparisons.items():
        if not c["flip_details"]:
            continue
        lines += [f"## {name}: flipped items", ""]
        lines += [
            f"- {f['item']}: {f['run_a']} -> {f['run_b']}" for f in c["flip_details"]
        ]
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--run-a", type=Path, required=True)
    parser.add_argument("--run-b", type=Path, required=True)
    parser.add_argument(
        "--benchmark", type=Path, default=None,
        help="benchmark payload both runs used (default: the frozen sample)",
    )
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args(argv)

    per_a, per_b = load_results(args.run_a), load_results(args.run_b)
    gold = gold_risk_by_item(args.benchmark)
    comparisons = {
        name: compare_strategy(per_a[name], per_b[name], gold)
        for name in sorted(set(per_a) & set(per_b))
    }
    args.out.write_text(
        render_markdown(args.run_a, args.run_b, comparisons), encoding="utf-8"
    )
    for name, c in comparisons.items():
        print(
            f"{name}: flips {c['label_flips']}/{c['labelled_items']} | "
            f"acc {c['accuracy_a']:.3f} -> {c['accuracy_b']:.3f} | "
            f"qa identical {c['qa_answer_identical']}/{c['qa_items']}"
        )
    shown = args.out.relative_to(ROOT) if args.out.is_relative_to(ROOT) else args.out
    print(f"wrote {shown}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
